name: Continuous Integration

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tox:
    name: Run tox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      - name: Install base and testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run Tox
        run: tox
